"""The DaVinci Resolve build of a phase: a Lua script installed in Resolve's Workspace > Scripts as
cg_solms_phaseN, which the free edition runs (it lets no outside Python drive it from 21.1 on).

    python solms.py resolve 1

The script imports the newest render of the phase (build/solms/phaseN/renders/), its music and
effects stems, makes a timeline at 30 fps with the picture on V1, the music on A1 and the effects
on A2, and marks every chapter (blue), war (red), battle (yellow) and Discord card (green).
It follows the Arabia build (cgvideo/timeline.py), which was measured on free Resolve 21.1:
menu scripts are handed a live `resolve`, their Lua has no `io`, and script windows are Studio-only.
"""

from __future__ import annotations

import json

from . import frame as F


def _s(x):
    return '"' + str(x).replace("\\", "/").replace('"', '\\"').replace("\n", " ") + '"'


def build(n: int, log=print):
    renders = sorted((F.build_dir(n) / "renders").glob(f"solms_phase{n}_*.mp4"))
    if not renders:
        raise SystemExit("render the phase first: python solms.py render %d" % n)
    cut = renders[-1]
    hf = F.build_dir(n) / "hf"
    D = json.loads((hf / "data.js").read_text(encoding="utf8")[len("window.DATA = "):].rstrip().rstrip(";"))
    fps = D["fps"]
    frames = int(round(D["duration"] * fps))
    stems = [hf / "assets" / "score_music.wav", hf / "assets" / "score_sfx.wav"]
    marks = []
    for sc in D["scenes"]:
        marks.append((round(sc["t0"] * fps), "Blue", sc["chapter"], f"Chapter: {sc['chapter']}", 1))
    for c in D["cards"]:
        if c["kind"] == "war":
            marks.append((round(c["t"] * fps), "Red", c["text"]["en"], f"War: {c['text']['en']} ({c['text']['sub']})", 30))
        if c["kind"] == "discord":
            marks.append((round(c["t"] * fps), "Green", "Discord", "The Discord card", 30))
    for l in D["lower"]:
        marks.append((round(l["t"] * fps), "Green", "Discord (lower third)", "The Discord lower third", 30))
    for w in D["wars"].values():
        for b in w["battles"]:
            marks.append((round(b["t"] * fps), "Yellow", f"Battle: {b['name']}",
                          " vs ".join(f"{s[0]} {s[1]:,}" for s in b["sides"]), 15))
    marks.sort()
    lua_marks = ",\n    ".join("{%d, %s, %s, %s, %d}" % (f, _s(c), _s(nm), _s(note), d) for f, c, nm, note, d in marks)
    name = f"Solms-America Phase {n}"
    lua = LUA.replace("@@CUT@@", _s(cut.as_posix())).replace("@@CUTNAME@@", cut.name) \
        .replace("@@MUSIC@@", _s(stems[0].as_posix())).replace("@@SFX@@", _s(stems[1].as_posix())) \
        .replace("@@MUSICNAME@@", stems[0].name).replace("@@SFXNAME@@", stems[1].name) \
        .replace("@@FRAMES@@", str(frames)).replace("@@LAST@@", str(frames - 1)).replace("@@FPS@@", str(fps)) \
        .replace("@@NAME@@", name).replace("@@MARKS@@", lua_marks).replace("@@N@@", str(n))
    out = F.build_dir(n) / f"resolve_phase{n}.lua"
    out.write_text(lua, encoding="utf8")
    import sys
    sys.path.insert(0, str(F.VIDEO))
    from cgvideo.timeline import resolve_scripts_dir
    target = resolve_scripts_dir()
    if target:
        target.mkdir(parents=True, exist_ok=True)
        (target / f"cg_solms_phase{n}.lua").write_text(lua, encoding="utf8")
        log(f"  installed: Workspace > Scripts > cg_solms_phase{n} ({target})")
    log(f"  {out} ({len(marks)} markers, {frames} frames, from {cut.name})")
    return out


LUA = r'''-- Generated by `python solms.py resolve @@N@@`. Do not edit: run it again instead.
-- Builds "Alternate History of Texas, Phase @@N@@" in DaVinci Resolve. Run it from Workspace > Scripts
-- with a project open; it reports in Workspace > Console.
local MANUAL = [==[Manual import (no scripting needed):
1. New project; File > Project Settings > Master Settings: timeline frame rate @@FPS@@ (before importing).
2. Media page: drag in @@CUT@@ and the stems @@MUSIC@@ and @@SFX@@.
3. Right-click the cut > Create New Timeline Using Selected Clips; put the stems on A2 and A3 at the start
   and mute the cut's own audio (it is the finished mix) if you balance them yourself.]==]
local function say(m) print(tostring(m)) end
local function try(f, ...) local ok, v = pcall(f, ...) if ok then return v end end

local function main()
  local r = resolve
  if not r and bmd and bmd.scriptapp then r = try(bmd.scriptapp, "Resolve") end
  if not r and Resolve then r = try(Resolve) end
  if not r then say("RESULT: this Resolve does not let scripts control projects.") say(MANUAL) return end
  say(tostring(try(function() return r:GetProductName() end)) .. " " .. tostring(try(function() return r:GetVersionString() end)))
  local pm = r:GetProjectManager()
  local project = pm and pm:GetCurrentProject()
  if not project then say("RESULT: no project is open. Open or create one, then run this again.") return end
  local rate = tonumber(project:GetSetting("timelineFrameRate"))
  if rate ~= @@FPS@@ then
    if project:SetSetting("timelineFrameRate", "@@FPS@@") then
      project:SetSetting("timelinePlaybackFrameRate", "@@FPS@@")
      say("Timeline frame rate set to @@FPS@@.")
    else
      say("WARNING: this project runs at " .. tostring(rate) .. " fps; use a new project at @@FPS@@ fps.")
    end
  end
  local mp = project:GetMediaPool()
  local items = mp:ImportMedia({@@CUT@@})
  if not items or #items == 0 then say("RESULT: the cut did not import: " .. @@CUT@@) return end
  local fr = tonumber(try(function() return items[1]:GetClipProperty("Frames") end))
  if fr and math.abs(fr - @@FRAMES@@) > 30 then
    say("STOP: Resolve reports " .. fr .. " frames, not @@FRAMES@@: it is showing an older copy. Close Resolve, reopen it, run this again.")
    return
  end
  local taken = {}
  for i = 1, (project:GetTimelineCount() or 0) do
    local t = project:GetTimelineByIndex(i); if t then taken[t:GetName()] = true end
  end
  local name, v = "@@NAME@@ v1", 1
  while taken[name] do v = v + 1; name = "@@NAME@@ v" .. v end
  local tl = nil
  local sound = try(function() return mp:ImportMedia({@@MUSIC@@, @@SFX@@}) end)
  if sound and #sound > 0 then
    local byname = {}
    for _, it in ipairs(sound) do
      local nm = try(function() return it:GetClipProperty("File Name") end); if nm then byname[nm] = it end
    end
    tl = try(function() return mp:CreateEmptyTimeline(name) end)
    if tl then
      project:SetCurrentTimeline(tl)
      local start = tl:GetStartFrame()
      local function put(item, media, track, last)
        local got = try(function() return mp:AppendToTimeline({{mediaPoolItem = item, startFrame = 0, endFrame = last or @@LAST@@,
          mediaType = media, trackIndex = track, recordFrame = start}}) end)
        if (not got or not got[1]) and media == 2 and not last then return put(item, media, track, @@LAST@@ - 1) end
        return got and got[1] or nil
      end
      if put(items[1], 1, 1) then
        while (try(function() return tl:GetTrackCount("audio") end) or 1) < 2 do
          if not try(function() return tl:AddTrack("audio", "stereo") end) then break end
        end
        local placed = 0
        for k, st in ipairs({{"@@MUSICNAME@@", "Music"}, {"@@SFXNAME@@", "Effects"}}) do
          local it = byname[st[1]] or sound[k]
          if it and put(it, 2, k) then placed = placed + 1; try(function() return tl:SetTrackName("audio", k, st[2]) end) end
        end
        say("Soundtrack: " .. placed .. " of 2 stems placed (A1 music, A2 effects); the picture is on V1.")
      else
        try(function() return mp:DeleteTimelines({tl}) end); tl = nil
      end
    end
  end
  if not tl then
    tl = mp:CreateTimelineFromClips(name, items)
    if not tl then say("RESULT: Resolve would not make the timeline.") return end
    project:SetCurrentTimeline(tl)
    say("Timeline made from the cut; its audio is the finished mix.")
  end
  local marks = {
    @@MARKS@@
  }
  local n = 0
  for _, m in ipairs(marks) do
    if try(function() return tl:AddMarker(m[1], m[2], m[3], m[4], m[5]) end) then n = n + 1 end
  end
  say("RESULT: " .. tl:GetName() .. ", " .. (tl:GetEndFrame() - tl:GetStartFrame()) .. " frames, " .. n .. " markers.")
end

local ok, err = pcall(main)
if not ok then print("ERROR: " .. tostring(err)) print(MANUAL) end
'''
